all: ly1 ly2 ly3 ly4 ly5 ly6


ly1:
	python ligeng_decoder.py -s 50 > lyken_output_50.txt

ly2:
	python ligeng_decoder.py -s 100 > lyken_output_100.txt

ly3:
	python ligeng_decoder.py -s 200 > lyken_output_200.txt

ly4:
	python ligeng_decoder.py -s 250 > lyken_output_250.txt

ly5:
	python ligeng_decoder.py -s 500 > lyken_output_500.txt

ly6:
	python ligeng_decoder.py -s 1000 > lyken_output_1000.txt
